apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
        deploymentconfig: mssql-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: quay.io/eformat/mssql-server:2019-RC1
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 31433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-internal
spec:
  ports:
    - name: mssql-internal
      port: 1433
      protocol: TCP
      targetPort: 1433
  selector:
    deploymentconfig: mssql-deployment
  sessionAffinity: None
  type: ClusterIP

